### ISSUE TITLE
cannot import wol

### ISSUE THREAD

**Issue by gnthibault** [mworion/mountwizzard#8]
Dear mworion,

I am extremely grateful to you for sharing your code like that. I am not (yet) owner of a 10micron mount, but I am planning to get one in the future.

As I was trying to play with mountwizzard, the mountwizzard script hit me with this error:

anaconda3/lib/python3.6/site-packages/pyfits-3.5-py3.6-linux-x86_64.egg/pyfits/__init__.py:22: PyFITSDeprecationWarning: PyFITS is deprecated, please use astropy.io.fits
  PyFITSDeprecationWarning)  # noqa
Traceback (most recent call last):
  File "./mountwizzard.py", line 58, in <module>
    from wakeonlan import wol
ImportError: cannot import name 'wol'

What version of wakeonlan are you using ? Is the software even compatible with python3 ?
Thank you very much in advance for your help.

**Comment by mworion** [comment]
Hi Thibault,

actally the better requirement would be wakeonlan==0.2.2, because the maintainer changed interfaces starting from 1.0.0 on. If you are familiar with python, please change line 58 in mountwizzard to 
from wakeonlan import send_magic_packet

and 250 to
send_magic_packet(self.ui.le_mountMAC.text().strip())

Than it will work from 1.0.0 on, too.

The pyrites package is depreciated but that does not harm.

Both topics are solved next official release MountWizzard3

Michel

**Comment by gnthibault** [comment]
Ok, thank you very much, I'lle wait for version 3 then
